```{r}
#| label: trendbasefunc
#| cache: true
#| cache.comments: false

trendbasegdmtfunc <- function(data, med, medname) {
  prop <- data %>%
    filter(!is.na(!!sym(med))) %>%
    group_by(indexyear_fac, .drop = F) %>%
    count(!!sym(med)) %>%
    mutate(
      tot = sum(n),
      p = n / tot * 100,
      pprint = fn(p, 0),
      level = medname
    ) %>%
    ungroup() %>%
    filter(!!sym(med) == "Yes") %>%
    select(indexyear_fac, p, pprint, level)
}

trendbasefunc <- function(data = rsdata, strata = NULL, addstrataname = NULL, ybreaks = seq(0, 100, 20), gdmt = F) {
  if (!gdmt) {
    nlevel <- nlevels(data %>% pull(!!sym(strata)))
    prop <- data %>%
      filter(!is.na(!!sym(strata))) %>%
      group_by(indexyear_fac, .drop = F) %>%
      count(!!sym(strata)) %>%
      mutate(
        tot = sum(n),
        p = n / tot * 100,
        pprint = fn(p, 0)
      ) %>%
      ungroup() %>%
      rename(level = !!sym(strata)) %>%
      mutate(
        level = paste0(addstrataname, level),
        level = str_replace_all(level, ">=", "\u2265"),
        level = str_replace_all(level, "<=", "\u2264"),
        level = fct_inorder(level)
      ) %>%
      arrange(level, indexyear_fac)
    nudgemy <- 5
  }

  if (gdmt) {
    nlevel <- 3
    rasi <- trendbasegdmtfunc(data = data, med = "shf_rasiarni", medname = "RASi/ARNi")
    bbl <- trendbasegdmtfunc(data = data, med = "shf_bbl", medname = "Beta-blocker")
    mra <- trendbasegdmtfunc(data = data, med = "shf_mra", medname = "MRA")

    prop <- bind_rows(rasi, bbl, mra) %>%
      mutate(level = fct_inorder(level))
    nudgemy <- -5
  }

  p <- prop %>% ggplot(
    aes(x = indexyear_fac, y = p, group = level)
  ) +
    geom_line(linewidth = 1.5, aes(color = level), show.legend = T) +
    geom_point(aes(col = level, shape = level, size = level), show.legend = T) +
    scale_color_manual(values = c(global_cols[1:nlevel])) +
    scale_shape_manual(values = c(global_shapes[1:nlevel])) +
    scale_size_manual(values = c(global_size[1:nlevel])) +
    scale_x_discrete(guide = guide_axis(n.dodge = 2)) +
    theme_classic() +
    theme(
      panel.grid.major.y = element_line(
        color = "lightgrey",
        linewidth = 0.5,
        linetype = 2
      ),
      text = element_text(size = 19, face = "bold"),
      axis.text = element_text(color = "black"),
      legend.position = "bottom",
      legend.title = element_blank(),
      legend.text = element_text(size = 20, face = "bold")
    ) +
    labs(x = "Year", y = "%") +
    scale_y_continuous(
      limits = c(min(ybreaks), max(ybreaks)), breaks = ybreaks # , expand = c(0, 0)
    ) +
    geom_text(
      data = prop %>% filter(indexyear_fac %in% c("2003", "2022")), # Filter data first
      aes(label = pprint),
      nudge_y = nudgemy,
      size = 5.5,
      color = rep(global_cols[1:nlevel], each = 2),
      fontface = "bold",
      check_overlap = F
    )

  if (output) {
    create_pptx(p)
  }
  p
}
```

```{r}
#| label: fig-baseadvhf
#| cache: true
#| cache.comments: false
#| dependson: trendbasefunc
#| fig-cap: "Temporal trends in baseline characteristics"
#| fig-subcap:
#|  - Age
#|  - Sex
#|  - CCI
#|  - GDMT
#| layout-ncol: 2
#| layout-nrow: 3

trendbasefunc(strata = "shf_age_cat", addstrataname = "Age (years) ")
trendbasefunc(strata = "shf_sex")
trendbasefunc(strata = "sos_com_charlsonci_cat", addstrataname = "CCI ")
trendbasefunc(gdmt = T)
```

```{r}
#| label: fig-baseadvhftreat
#| cache: true
#| cache.comments: false
#| dependson: trendbasefunc
#| fig-cap: "Temporal trends in baseline characteristics for patients eligible for AdvHF therapies"
#| fig-subcap:
#|  - Sex
#|  - CCI
#|  - GDMT
#| layout-ncol: 2
#| layout-nrow: 3

trendbasefunc(data = rsdata %>% filter(advhftreat == "Yes"), strata = "shf_sex")
trendbasefunc(data = rsdata %>% filter(advhftreat == "Yes"), strata = "sos_com_charlsonci_cat", addstrataname = "CCI ")
trendbasefunc(data = rsdata %>% filter(advhftreat == "Yes"), gdmt = T)
```
