```{r}
#| label: trendprevfunc
#| cache: true
#| cache.comments: false

trendprevfunc <- function(data, xvar, eventname, ybreaks = seq(0, 100, 20)) {
  prop <- data %>%
    group_by(indexyear_fac) %>%
    count(!!sym(xvar)) %>%
    mutate(
      tot = sum(n),
      p = n / tot * 100
    ) %>%
    ungroup() %>%
    filter(!!sym(xvar) == "Yes")

  p <- prop %>% ggplot(
    aes(x = indexyear_fac, y = p, group = 1)
  ) +
    geom_line(linewidth = 1, colour = global_cols[1]) +
    geom_point(size = 2, colour = global_cols[1]) +
    scale_x_discrete(guide = guide_axis(n.dodge = 2)) +
    theme_classic() +
    theme(
      panel.grid.major = element_line(
        color = "lightgrey",
        linewidth = 0.5,
        linetype = 2
      ),
      text = element_text(size = 15, face = "bold"),
      axis.text = element_text(color = "black")
    ) +
    labs(x = "Year", y = paste0(eventname, ", %")) +
    scale_y_continuous(
      limits = c(min(ybreaks), max(ybreaks)), breaks = ybreaks # , expand = c(0, 0)
    )

  if (output) {
    create_pptx(p)
  }
  p
}
trendprevtabfunc <- function(data, xvar) {
  prop <- data %>%
    group_by(indexyear_fac) %>%
    count(!!sym(xvar)) %>%
    mutate(
      np = paste0(n, " (", fn(n / sum(n) * 100, 1), "%)")
    ) %>%
    ungroup() %>%
    filter(!!sym(xvar) == "Yes") %>%
    select(indexyear_fac, np)

  cl <- c("Year", "n (%)")

  if (output) {
    make_one_xlsxsheet(prop, colnames = cl)
  }

  default_kable(prop,
    col.names = cl
  )
}
```

```{r}
#| label: fig-advhftreat
#| cache: true
#| cache.comments: false
#| dependson: trendprevfunc
#| fig-cap: "Temporal trends eligible for AdvHF therapies"
trendprevfunc(data = rsdata, xvar = "advhftreat", eventname = "Eligible for AdvHF therapies")
```

```{r}
#| label: tbl-advhftreat
#| cache: true
#| cache.comments: false
#| dependson: trendprevfunc
#| tbl-cap: "Temporal trends eligible for AdvHF therapies"
#| tbl-pos: "H"

trendprevtabfunc(data = rsdata, xvar = "advhftreat")
```
