```{r}
#| label: trendfunc
#| cache: true
#| cache.comments: false

trendfunc <- function(data = rsdata, event, time, eventname, strata = NULL, addstrataname = NULL, ybreaks = NULL, yearvar = "indexyear_fac") {
  r <- data %>%
    mutate(!!sym(yearvar) := droplevels(!!sym(yearvar))) %>%
    group_by(!!sym(strata), !!sym(yearvar)) %>%
    summarise(
      ev = sum(!!sym(event) == "Yes"),
      s = sum(!!sym(time) / 365.25),
      .groups = "drop"
    ) %>%
    rename(level = !!sym(strata)) %>%
    mutate(
      rate = ev / s * 100,
      rateprint = fn(rate, 0),
      level = paste0(addstrataname, level),
      level = str_replace_all(level, ">=", "\u2265"),
      level = str_replace_all(level, "<=", "\u2264"),
      level = fct_inorder(level)
    )
  levs <- levels(data %>% pull(!!sym(yearvar)))

  if (strata == "all") {
    p <- r %>% ggplot(
      aes(x = !!sym(yearvar), y = rate, group = 1)
    ) +
      geom_line(linewidth = 1.5, colour = global_cols[1]) +
      geom_point(size = 3.5, colour = global_cols[1]) +
      scale_x_discrete(guide = guide_axis(n.dodge = 2)) +
      theme_classic() +
      theme(
        panel.grid.major.y = element_line(
          color = "lightgrey",
          linewidth = 0.5,
          linetype = 2
        ),
        text = element_text(size = 19, face = "bold"),
        axis.text = element_text(color = "black")
      ) +
      labs(x = "Year", y = paste0(eventname, " / 100 person-years")) +
      geom_text(
        data = r %>% filter(!!sym(yearvar) %in% c(first(levs), last(levs))), # Filter data first
        aes(label = rateprint),
        nudge_y = max(ybreaks) * 0.05,
        size = 5.5,
        color = global_cols[1],
        fontface = "bold"
      )
  }

  if (strata != "all") {
    p <- r %>% ggplot(
      aes(x = !!sym(yearvar), y = rate, group = level)
    ) +
      geom_line(linewidth = 1.5, aes(color = level), show.legend = T) +
      geom_point(aes(col = level, shape = level, size = level), show.legend = T) +
      scale_color_manual(values = c(global_cols[1:2])) +
      scale_shape_manual(values = c(global_shapes[1:2])) +
      scale_size_manual(values = c(global_size[1:2])) +
      scale_x_discrete(guide = guide_axis(n.dodge = 2)) +
      theme_classic() +
      theme(
        panel.grid.major.y = element_line(
          color = "lightgrey",
          linewidth = 0.5,
          linetype = 2
        ),
        text = element_text(size = 19, face = "bold"),
        axis.text = element_text(color = "black"),
        legend.position = "bottom",
        legend.title = element_blank(),
        legend.text = element_text(size = 20, face = "bold")
      ) +
      labs(x = "Year", y = paste0(eventname, " / 100 person-years")) +
      geom_text(
        data = r %>% filter(!!sym(yearvar) %in% c(first(levs), last(levs))), # Filter data first
        aes(label = rateprint),
        nudge_y = max(ybreaks) * 0.05,
        size = 5.5,
        color = rep(global_cols[1:2], each = 2),
        fontface = "bold"
      )
  }

  if (!is.null(ybreaks)) {
    p <- p + scale_y_continuous(
      limits = c(min(ybreaks), max(ybreaks)), breaks = ybreaks # , expand = c(0, 0)
    )
  }
  if (output) {
    create_pptx(p)
  }
  p
}
```

```{r}
#| label: fig-death
#| cache: true
#| cache.comments: false
#| dependson: trendfunc
#| fig-cap: "Temporal trends death"
#| fig-subcap:
#| - All
#| - Age
#| - Sex
#| - Patients eligible for advanced HF therapy
#| layout-ncol: 2
#| layout-nrow: 2

i <- 1
ybreaks <- seq(0, 100, 20)

trendfunc(event = outvars$var[i], time = outvars$time[i], eventname = outvars$shortname[i], strata = "all", ybreaks = ybreaks)
trendfunc(event = outvars$var[i], time = outvars$time[i], eventname = outvars$shortname[i], strata = "shf_age_cat", addstrataname = "Age (years) ", ybreaks = ybreaks)
trendfunc(event = outvars$var[i], time = outvars$time[i], eventname = outvars$shortname[i], strata = "shf_sex", ybreaks = ybreaks)
trendfunc(data = rsdata %>% filter(advhftreat == "Yes"), event = outvars$var[i], time = outvars$time[i], eventname = outvars$shortname[i], strata = "all", ybreaks = ybreaks)
```

```{r}
#| label: fig-cvdeath
#| cache: true
#| cache.comments: false
#| dependson: trendfunc
#| fig-cap: "Temporal trends CV death"
#| fig-subcap:
#| - All
#| - Age
#| - Sex
#| - Patients eligible for advanced HF therapy
#| layout-ncol: 2
#| layout-nrow: 2

i <- 2
ybreaks <- seq(0, 100, 20)

trendfunc(event = outvars$var[i], time = outvars$time[i], eventname = outvars$shortname[i], strata = "all", ybreaks = ybreaks)
trendfunc(event = outvars$var[i], time = outvars$time[i], eventname = outvars$shortname[i], strata = "shf_age_cat", addstrataname = "Age (years) ", ybreaks = ybreaks)
trendfunc(event = outvars$var[i], time = outvars$time[i], eventname = outvars$shortname[i], strata = "shf_sex", ybreaks = ybreaks)
trendfunc(data = rsdata %>% filter(advhftreat == "Yes"), event = outvars$var[i], time = outvars$time[i], eventname = outvars$shortname[i], strata = "all", ybreaks = ybreaks)
```


```{r}
#| label: fig-noncvdeath
#| cache: true
#| cache.comments: false
#| dependson: trendfunc
#| fig-cap: "Temporal trends Non-CV death"
#| fig-subcap:
#| - All
#| - Age
#| - Sex
#| - Patients eligible for advanced HF therapy
#| layout-ncol: 2
#| layout-nrow: 2

i <- 3
ybreaks <- seq(0, 20, 5)

trendfunc(event = outvars$var[i], time = outvars$time[i], eventname = outvars$shortname[i], strata = "all", ybreaks = ybreaks, yearvar = "indexyear_cat_fac")
trendfunc(event = outvars$var[i], time = outvars$time[i], eventname = outvars$shortname[i], strata = "shf_age_cat", addstrataname = "Age (years) ", ybreaks = ybreaks, yearvar = "indexyear_cat_fac")
trendfunc(event = outvars$var[i], time = outvars$time[i], eventname = outvars$shortname[i], strata = "shf_sex", ybreaks = ybreaks, yearvar = "indexyear_cat_fac")
trendfunc(data = rsdata %>% filter(advhftreat == "Yes"), event = outvars$var[i], time = outvars$time[i], eventname = outvars$shortname[i], strata = "all", ybreaks = ybreaks, yearvar = "indexyear_cat_fac")
```


```{r}
#| label: fig-lvad
#| cache: true
#| cache.comments: false
#| dependson: trendfunc
#| fig-cap: "Temporal trends LVAD"
#| fig-subcap:
#| - All
#| - Patients eligible for advanced HF therapy
#| layout-ncol: 2
#| layout-nrow: 2

i <- 4
ybreaks <- seq(0, 10, 2)

trendfunc(event = outvars$var[i], time = outvars$time[i], eventname = outvars$shortname[i], strata = "all", ybreaks = ybreaks, yearvar = "indexyear_cat_fac")

trendfunc(
  data = rsdata %>% filter(advhftreat == "Yes"), event = outvars$var[i], time = outvars$time[i], eventname = outvars$shortname[i], strata = "all", ybreaks = ybreaks, yearvar = "indexyear_cat_fac"
)
```


```{r}
#| label: fig-htx
#| cache: true
#| cache.comments: false
#| dependson: trendfunc
#| fig-cap: "Temporal trends Htx"
#| fig-subcap:
#| - All
#| - Patients eligible for advanced HF therapy
#| layout-ncol: 2
#| layout-nrow: 2

i <- 5
ybreaks <- seq(0, 10, 2)

trendfunc(event = outvars$var[i], time = outvars$time[i], eventname = outvars$shortname[i], strata = "all", ybreaks = ybreaks, yearvar = "indexyear_cat_fac")
trendfunc(data = rsdata %>% filter(advhftreat == "Yes"), event = outvars$var[i], time = outvars$time[i], eventname = outvars$shortname[i], strata = "all", ybreaks = ybreaks, yearvar = "indexyear_cat_fac")
```
