```{r}
#| label: trendprevadvhffunc
#| cache: true
#| cache.comments: false

propadvhf <- rsdataadvhf %>%
  mutate(indexyear_fac = factor(shf_indexyear)) %>%
  group_by(indexyear_fac) %>%
  count(advhf) %>%
  mutate(
    tot = sum(n),
    p = n / tot * 100,
    pprint = fn(p, 0),
    np = paste0(n, "/", tot, " (", pprint, "%)"),
  ) %>%
  ungroup() %>%
  filter(advhf == "Yes")
```

```{r}
#| label: fig-advhf
#| cache: true
#| cache.comments: false
#| dependson: trendprevadvhffunc
#| fig-cap: "Temporal trends AdvHF"

p <- propadvhf %>% ggplot(
  aes(x = indexyear_fac, y = p, group = 1)
) +
  geom_line(linewidth = 1.5, colour = global_cols[1]) +
  geom_point(size = 3.5, colour = global_cols[1]) +
  scale_x_discrete(guide = guide_axis(n.dodge = 2)) +
  theme_classic() +
  theme(
    panel.grid.major.y = element_line(
      color = "lightgrey",
      linewidth = 0.5,
      linetype = 2
    ),
    text = element_text(size = 19, face = "bold"),
    axis.text = element_text(color = "black")
  ) +
  labs(x = "Year", y = "AdvHF, %") +
  scale_y_continuous(
    limits = c(0, 100), breaks = seq(0, 100, 20)
  ) +
  geom_text(
    data = propadvhf %>% filter(indexyear_fac %in% c("2003", "2022")), # Filter data first
    aes(label = pprint),
    nudge_y = 5,
    size = 5.5,
    color = global_cols[1],
    fontface = "bold"
  )

if (output) {
  create_pptx(p)
}
p
```

```{r}
#| label: tbl-advhf
#| cache: true
#| cache.comments: false
#| dependson: trendprevadvhffunc
#| tbl-cap: "Temporal trends AdvHF"
#| tbl-pos: "H"

proptab <- propadvhf %>%
  select(indexyear_fac, np)

cl <- c("Year", "n/N (%)")

if (output) {
  make_one_xlsxsheet(proptab, colnames = cl)
}

default_kable(proptab,
  col.names = cl
)
```

```{r}
#| label: trendprevfunc
#| cache: true
#| cache.comments: false

prop <- rsdata %>%
  group_by(indexyear_fac) %>%
  count(advhftreat) %>%
  mutate(
    tot = sum(n),
    p = n / tot * 100,
    pprint = fn(p, 0),
    np = paste0(n, "/", tot, " (", pprint, "%)"),
  ) %>%
  ungroup() %>%
  filter(advhftreat == "Yes")
```

```{r}
#| label: fig-advhftreat
#| cache: true
#| cache.comments: false
#| dependson: trendprevfunc
#| fig-cap: "Temporal trends eligible for AdvHF therapies"

p <- prop %>% ggplot(
  aes(x = indexyear_fac, y = p, group = 1)
) +
  geom_line(linewidth = 1.5, colour = global_cols[1]) +
  geom_point(size = 3.5, colour = global_cols[1]) +
  scale_x_discrete(guide = guide_axis(n.dodge = 2)) +
  theme_classic() +
  theme(
    panel.grid.major.y = element_line(
      color = "lightgrey",
      linewidth = 0.5,
      linetype = 2
    ),
    text = element_text(size = 19, face = "bold"),
    axis.text = element_text(color = "black")
  ) +
  labs(x = "Year", y = "Eligible for AdvHF therapies, %") +
  scale_y_continuous(
    limits = c(0, 100), breaks = seq(0, 100, 20)
  ) +
  geom_text(
    data = prop %>% filter(indexyear_fac %in% c("2003", "2022")), # Filter data first
    aes(label = pprint),
    nudge_y = 5,
    size = 5.5,
    color = global_cols[1],
    fontface = "bold"
  )

if (output) {
  create_pptx(p)
}
p
```

```{r}
#| label: tbl-advhftreat
#| cache: true
#| cache.comments: false
#| dependson: trendprevfunc
#| tbl-cap: "Temporal trends eligible for AdvHF therapies"
#| tbl-pos: "H"

proptab <- prop %>%
  select(indexyear_fac, np)

cl <- c("Year", "n/N (%)")

if (output) {
  make_one_xlsxsheet(proptab, colnames = cl)
}

default_kable(proptab,
  col.names = cl
)
```

